### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

### ISSUE THREAD

**Issue by Francis621** [thoughtworksarts/EmoPy#49] opened 2019-12-11 06:37 UTC
When I  run "python fermodel_example.py" , the system said:AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'
What is the solutions?

**Comment by cptanalatriste** [comment] 2019-12-12 12:34
Hello!

I run into a similar problem earlier, due to an unsupported version of Keras. Please run the following in your environment:

`pip show keras
`

If the version is >= 2.3, you're probably facing the same issue. I fixed it by forcing an install of version 2.2 of the package, by running this command in my environment:

`pip install 'keras==2.2.0'
`

Please let me know if the issue persists.

**Comment by satishdash** [comment] 2019-12-12 13:44
Hey @cptanalatriste  keras==2.2.4 is a solution that we are now going with. And yes an exact version of Keras 2.2.X  but less than 2.3.0 solves the issue. Thanks. I believe this issue can be closed now!
@xuv any opinions?

**Comment by cptanalatriste** [comment] 2019-12-12 13:58
Duplicate of #44

**Comment by cptanalatriste** [comment] 2019-12-12 15:03
@satishdash I just played safe and tried the minimal version supported in `requirements.txt` . If 2.2.4 also does the trick, go for it :D

**Closed** 2019-12-13 09:09 UTC
